name: Test Apptainer upload

on:
  push:
    branches:
      - openneuropet_apptainer

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build container images
        run: |
          set -e
          bash build.sh

      - name: Export Docker images
        run: |
          set -e
          docker save -o api_image.tar ezbids-api
          docker save -o handler_image.tar ezbids-handler
          docker save -o ui_image.tar ezbids-ui
          docker save -o telemetry_image.tar ezbids-telemetry
        working-directory: ./apptainer

      - name: Run Apptainer
        run: |
          set -e
          bash run_apptainer.sh
        working-directory: ./apptainer

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Verify uv installation
        run: uv --version

      - name: Run upload test
        run: make test-upload
